#!/bin/sh
remotehost='10.64.128.0/24'
myhost='10.64.128.3/32'
friendhost='10.64.128.5/32'
any='0.0.0.0/0'

# ルールの初期化
iptables -F
iptables -X

# 基本ポリシ
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# 追加ポリシ
iptables -A INPUT -p tcp -s $any -d $myhost --dport 21 -j ACCEPT
iptables -A OUTPUT -p tcp -s $myhost --sport 21 -d $any -j ACCEPT
iptables -A INPUT -p tcp -s $any -d $myhost --dport 20 -j ACCEPT
iptables -A OUTPUT -p tcp -s $myhost --sport 20 -d $any -j ACCEPT

iptables -A OUTPUT -p tcp -s $myhost -d $friendhost --dport 21 -j ACCEPT
iptables -A INPUT -p tcp -s $friendhost --sport 21 -d $myhost -j ACCEPT
iptables -A OUTPUT -p tcp -s $myhost -d $friendhost --dport 20 -j ACCEPT
iptables -A INPUT -p tcp -s $friendhost --sport 20 -d $myhost -j ACCEPT
