#!/bin/sh
remotehost='10.64.128.0/24'
myhost='10.64.18.3/32'
friendhost='10.64.128.5/32'
any='0.0.0.0/0'

# ルールの初期化
iptables -F
iptables -X

# 基本ポリシ
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -N LOGGING
iptables -A LOGGING -j LOG --log-level warning --log-prefix "FILTER DROP"
iptables -A LOGGING -j DROP
iptables -A INPUT -j LOGGING
iptables -A OUTPUT -j LOGGING
