#!/bin/zsh 
remotehost='10.64.128.0/24'
myhost='10.64.128.26/32'
friendhost='10.64.128.27/32'
any='0.0.0.0/0'

#ルールの初期化
iptables -F
iptables -X

#ポリシー
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP





