#!/bin/zsh 
remotehost='10.64.128.0/24'
myhost='10.64.128.26/32'
friendhost='10.64.128.27/32'
any='0.0.0.0/0'

#ルールの初期化
iptables -F
iptables -X

#ポリシー
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

iptables -A OUTPUT -p icmp --icmp-type echo-request -s $myhost -d $any -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-reply -s $any -d $myhost -j ACCEPT
#iptables -A INPUT -p icmp --icmp-type echo-reply -s $any -d $myhost -m limit --limit 1/m --limit-burst 10 -j ACCEPT

iptables -A INPUT -p icmp --icmp-type echo-request -s $any -d $myhost -m limit --limit 1/m --limit-burst 10 -j ACCEPT
#iptables -A INPUT -p icmp --icmp-type echo-request -s $any -d $myhost -j ACCEPT
iptables -A OUTPUT -p icmp --icmp-type echo-reply -s $myhost -d $any -j ACCEPT
